# Generated by Django 5.2.11 on 2026-02-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('verdict', models.CharField(choices=[('true_positive', 'True Positive'), ('false_positive', 'False Positive'), ('benign', 'Benign'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blast_radius', models.JSONField(default=dict)),
                ('asset_context', models.JSONField(default=dict)),
                ('risk_context', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AlertSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('detection_logic', models.JSONField(default=dict)),
                ('evidence', models.JSONField(default=list)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='detections.alert')),
            ],
        ),
    ]
