# Generated by Django 5.2.11 on 2026-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='alert',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='destination_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='mitre_tactic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='source_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
