# Generated by Django 5.2.11 on 2026-02-14 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0.0)),
                ('matches_found', models.IntegerField(default=0)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('result_data', models.JSONField(default=dict)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hunting.hunt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
