# Generated by Django 5.2.11 on 2026-02-14 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunting', '0002_huntresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hunt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='hunt',
            name='confidence',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='hunt',
            name='data_processed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hunt',
            name='hypothesis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hunt',
            name='log_source',
            field=models.CharField(default='conn', max_length=50),
        ),
        migrations.AddField(
            model_name='hunt',
            name='matches_found',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hunt',
            name='sql_query',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hunt',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='hunt',
            name='time_range',
            field=models.CharField(default='Last 24h', max_length=50),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='query',
            field=models.TextField(blank=True, default=''),
        ),
    ]
