# Generated by Django 5.2.11 on 2026-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
                ('severity', models.CharField(default='info', max_length=20)),
                ('content', models.TextField()),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
