/**
 * Zeek Field Catalog Utilities — Single Source of Truth
 *
 * Parses zeek_field_catalog.json (auto-generated by generate_field_catalog.go)
 * and exposes helpers used by:
 *   • SchemaExplorer component (system-wide schema browser)
 *   • Rule Builder (log source dropdowns, field pickers)
 *   • Threat Hunting (data source selectors, SQL sidebar)
 *   • Logs Page (field reference)
 *   • Any future log-source-aware component
 */

import fieldCatalog from './zeek_field_catalog.json';

// ─── Types ───────────────────────────────────────────────────
export type FieldContext = 'hunting' | 'rules' | 'logs' | 'raw';
export type FieldGroup = 'most_used' | 'enriched' | 'others' | 'system';

export interface LogField {
    name: string;
    type: string;
    parquet: string;
    ui_visible: boolean;
    group?: FieldGroup;
    label?: string;
    description?: string;
    contexts?: FieldContext[];
    promoted_from?: string;
}

export interface LogSource {
    name: string;
    raw_fields: LogField[];
    normalized_enriched: LogField[];
}

export interface GroupedFields {
    mostUsed: LogField[];
    enriched: LogField[];
    others: LogField[];
}

export interface LogSourceMeta {
    name: string;
    nameLower: string;
    totalFields: number;
    visibleFields: number;
    hasMostUsed: boolean;
}

// ─── Core Data ───────────────────────────────────────────────
const zeekLogs: LogSource[] = (fieldCatalog as any).zeek_logs;

// ─── Public API ──────────────────────────────────────────────

/** All log source names (e.g. "CONN", "DNS", "HTTP") */
export const getLogSources = (): string[] =>
    zeekLogs.map(l => l.name);

/** Retrieve a single log source by name */
export const getLogSource = (name: string): LogSource | undefined =>
    zeekLogs.find(l => l.name.toUpperCase() === name.toUpperCase());

/**
 * Metadata summary for every log source — useful for table listings.
 */
export const getLogSourcesMeta = (): LogSourceMeta[] =>
    zeekLogs.map(src => {
        const all = [...src.raw_fields, ...src.normalized_enriched];
        const visible = all.filter(f => f.ui_visible);
        return {
            name: src.name,
            nameLower: src.name.toLowerCase(),
            totalFields: all.length,
            visibleFields: visible.length,
            hasMostUsed: visible.some(f => f.group === 'most_used'),
        };
    });

/**
 * All ui_visible fields for a given source, merged from raw + enriched,
 * split into { mostUsed, enriched, others }.
 */
export const getFieldsForSource = (sourceName: string): GroupedFields => {
    const source = getLogSource(sourceName);
    if (!source) return { mostUsed: [], enriched: [], others: [] };

    const allFields = [
        ...source.raw_fields,
        ...source.normalized_enriched,
    ].filter(f => f.ui_visible);

    return {
        mostUsed: allFields.filter(f => f.group === 'most_used'),
        enriched: allFields.filter(f => f.group === 'enriched'),
        others: allFields.filter(f => f.group === 'others'),
    };
};

/**
 * All ui_visible fields filtered by a specific context (hunting / rules / logs).
 * Returns only fields that are relevant to the given section.
 */
export const getFieldsForContext = (sourceName: string, context: FieldContext): GroupedFields => {
    const source = getLogSource(sourceName);
    if (!source) return { mostUsed: [], enriched: [], others: [] };

    const allFields = [
        ...source.raw_fields,
        ...source.normalized_enriched,
    ].filter(f => f.ui_visible && f.contexts && f.contexts.includes(context));

    return {
        mostUsed: allFields.filter(f => f.group === 'most_used'),
        enriched: allFields.filter(f => f.group === 'enriched'),
        others: allFields.filter(f => f.group === 'others'),
    };
};

/**
 * Flat list of all visible fields for a source (most-used first, then enriched, then others).
 * Convenience helper for simpler consumers.
 */
export const getAllVisibleFields = (sourceName: string): LogField[] => {
    const { mostUsed, enriched, others } = getFieldsForSource(sourceName);
    return [...mostUsed, ...enriched, ...others];
};

/**
 * Flat list of all visible fields for a source filtered by context.
 */
export const getAllVisibleFieldsForContext = (sourceName: string, context: FieldContext): LogField[] => {
    const { mostUsed, enriched, others } = getFieldsForContext(sourceName, context);
    return [...mostUsed, ...enriched, ...others];
};
