# Generated by Django 5.2.11 on 2026-02-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('type', models.CharField(choices=[('threshold', 'Threshold'), ('query', 'Query')], max_length=20)),
                ('query', models.TextField()),
                ('threshold', models.IntegerField(default=1)),
                ('time_window', models.CharField(default='5m', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mitre_tactic', models.CharField(blank=True, max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RuleStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detections_24h', models.IntegerField(default=0)),
                ('detections_7d', models.IntegerField(default=0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('avg_execution_time_ms', models.IntegerField(default=0)),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='rules.rule')),
            ],
        ),
    ]
