# Generated by Django 5.2.11 on 2026-02-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('malware', 'Malware'), ('exfiltration', 'Exfiltration'), ('lateral', 'Lateral Movement'), ('recon', 'Reconnaissance')], max_length=50)),
                ('signals', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('detection_logic', models.TextField()),
                ('thresholds', models.JSONField(default=dict)),
                ('required_fields', models.JSONField(default=list)),
                ('grouping_entity', models.CharField(max_length=50)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='usecases.usecase')),
            ],
        ),
    ]
