# Generated by Django 5.2.11 on 2026-02-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(default='unknown', max_length=50)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('vuln_count', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=0)),
                ('segment', models.CharField(blank=True, max_length=100)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_threat', models.BooleanField(default=False)),
                ('threat_confidence', models.IntegerField(default=0)),
            ],
        ),
    ]
